# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OrganisationModule' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OrganisationModule
pod 'Alamofire', '~> 5.2'
pod 'FontAwesome.swift'
pod 'FontAwesomeKit.Swift'


end
